# Generated by Django 5.2.7 on 2025-10-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='счетчик просмотров'),
        ),
    ]
